#!/bin/bash
# This script is used to calculate a per minute hit rate
# from a Squid running as a transparent proxy
# Created: 2016/11/19 14.00
# By ecutuning <at> outlook.com

# More OIDs
# http://wiki.squid-cache.org/Features/Snmp

REQ_OID=".1.3.6.1.4.1.3495.1.3.2.1.1.0"
HIT_OID=".1.3.6.1.4.1.3495.1.3.2.1.2.0"
VERSION=2c
COMM=public
HOST="192.168.1.1"
SLEEP_TIMER="60"

while true; do

        NOW=$(date +"%Y/%m/%d %H:%M:%S")
        REQ_1=`snmpwalk -v$VERSION -c $COMM $HOST $REQ_OID | awk '{print $4}'`
        HIT_1=`snmpwalk -v$VERSION -c $COMM $HOST $HIT_OID | awk '{print $4}'`
        sleep $SLEEP_TIMER
        REQ_2=`snmpwalk -v$VERSION -c $COMM $HOST $REQ_OID | awk '{print $4}'`
        HIT_2=`snmpwalk -v$VERSION -c $COMM $HOST $HIT_OID | awk '{print $4}'`

        REQ=`expr $REQ_2 - $REQ_1`
        HIT=`expr $HIT_2 - $HIT_1`
        HITRATE=$(awk "BEGIN { pc=100*${HIT}/${REQ}; i=int(pc); print (pc-i<0.5)?i:i+1 }")

        printf "%s %4d %s %4d %s %s %2d %s\n" "[$NOW]" $REQ "Requests " $HIT "Hits    " "[ Hit Rate: " $HITRATE "% ]"

done
